# ACCOUNT_LEN = 20
# DRONE_LEN = 20
# FLAW_LEN = 20
# FLIGHT_LEN = 20
# FLIGHTSCHEDULE_LEN = 20
# LOG_LEN = 10    # ATTENTION: LOGS FOR ONE FLIGHT
# OBJECT_LEN = 20
# OBJECTTYPE_LEN = 4
# POINT_LEN = 20
# POINTTYPE_LEN = 14
# ROLE_LEN = 3    
# ROUTE_LEN = 20
# USER_LEN = 20

ACCOUNT_LEN = 40
DRONE_LEN = 20
FLAW_LEN = 50
FLIGHT_LEN = 1000
FLIGHTSCHEDULE_LEN = 400
LOG_LEN = 15   # ATTENTION: LOGS FOR ONE FLIGHT
OBJECT_LEN = 1000
OBJECTTYPE_LEN = 4
POINT_LEN = 500
POINTTYPE_LEN = 14
ROLE_LEN = 3
ROUTE_LEN = 200
USER_LEN = 40

Wroclaw_Longitude = 17
Wroclaw_Latitude = 51

SCRIPT_FILENAME = "plik.txt"
