# THIS FILE DESCRIBES HOW MANY ROWS WILL BE ADDED TO DB (EXCLUDING pointtype, objecttype, role)

# ACCOUNT_LEN = 20
# DRONE_LEN = 20
# FLAW_LEN = 20
# FLIGHT_LEN = 20
# FLIGHTSCHEDULE_LEN = 20
# LOG_LEN = 10    # ATTENTION: LOGS FOR ONE FLIGHT
# OBJECT_LEN = 30    # ATTENTION: OBJECT FOR ONE FLIGHT
# POINT_ON_ROUTE = 10 # ATTENTION: POINTS ON ROUTE FOR ONE ROUTE
# OBJECTTYPE_LEN = 4
# POINT_LEN = 20
# POINTTYPE_LEN = 14
# ROLE_LEN = 3    
# ROUTE_LEN = 20
# USER_LEN = 20

ACCOUNT_LEN = 100
DRONE_LEN = 100
FLAW_LEN = 100
FLIGHT_LEN = 1000
FLIGHTSCHEDULE_LEN = 400
LOG_LEN = 30   # ATTENTION: LOGS FOR ONE FLIGHT
OBJECT_LEN = 30    # ATTENTION: OBJECT FOR ONE FLIGHT
POINT_ON_ROUTE = 10 # ATTENTION: POINTS ON ROUTE FOR ONE ROUTE
OBJECTTYPE_LEN = 4
POINT_LEN = 30
POINTTYPE_LEN = 14
ROLE_LEN = 3
ROUTE_LEN = 200
USER_LEN = 100

Wroclaw_Longitude = 17
Wroclaw_Latitude = 51

SCRIPT_FILENAME = "gavron_createdb_script.sql"